services:
  spring-boot-app:
    image: devops2
    ports:
      - '0.0.0.0:8091:8091'
    environment:
      - server.port=8091
      - spring.datasource.url=jdbc:mysql://localhost:3306/api_etudiant
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'api_etudiant'
      MYSQL_ROOT_USERNAME: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '0.0.0.0:3306:3306'
    volumes:
      - api_etudiant:/var/lib/mysql
  volumes:
    api_etudiant:
